-- CREACIÓN DE LA BASE DE DATOS
--CREATE DATABASE SAZON_LOCAL;
--USE SAZON_LOCAL;

-- BORRAR SECUENCIAS
DROP SEQUENCE IF EXISTS Seq_Roles;
DROP SEQUENCE IF EXISTS Seq_Categorias;
DROP SEQUENCE IF EXISTS Seq_Usuarios;
DROP SEQUENCE IF EXISTS Seq_Direcciones;
DROP SEQUENCE IF EXISTS Seq_Validaciones;
DROP SEQUENCE IF EXISTS Seq_Fincas;
DROP SEQUENCE IF EXISTS Seq_Subcategorias;
DROP SEQUENCE IF EXISTS Seq_UnidadMedida;
DROP SEQUENCE IF EXISTS Seq_Productos;
DROP SEQUENCE IF EXISTS Seq_Carrito;
DROP SEQUENCE IF EXISTS Seq_Pedidos;
DROP SEQUENCE IF EXISTS Seq_DetallesPedido;
DROP SEQUENCE IF EXISTS Seq_Pagos;
DROP SEQUENCE IF EXISTS Seq_Mensajes;

-- BORRAR PROCEDURES
DROP PROCEDURE IF EXISTS SP_NEXT_ID;

-- BORRAR TABLAS SI EXISTEN
DROP TABLE IF EXISTS MENSAJES;
DROP TABLE IF EXISTS PAGOS;
DROP TABLE IF EXISTS DETALLE_PEDIDOS;
DROP TABLE IF EXISTS PEDIDOS;
DROP TABLE IF EXISTS CARRITO_ITEMS;
DROP TABLE IF EXISTS PRODUCTOS;
DROP TABLE IF EXISTS UNIDAD_MEDIDAS;
DROP TABLE IF EXISTS SUBCATEGORIAS;
DROP TABLE IF EXISTS FINCAS;
DROP TABLE IF EXISTS VALIDACIONES;
DROP TABLE IF EXISTS DIRECCIONES;
DROP TABLE IF EXISTS KEYS_USUARIOS;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS CATEGORIAS;
DROP TABLE IF EXISTS ROLES;

-- CREACION SECUENCIAS
CREATE SEQUENCE Seq_Roles START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Categorias START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Usuarios START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Direcciones START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Validaciones START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Fincas START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Subcategorias START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_UnidadMedida START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Productos START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Carrito START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Pedidos START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_DetallesPedido START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Pagos START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Mensajes START WITH 1 INCREMENT BY 1;

-- CREACION TABLAS
CREATE TABLE ROLES (
    ID_ROL INT PRIMARY KEY,
    NOMBRE NVARCHAR(50) NOT NULL
);

CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(255),
    ESTA_ACTIVA BIT DEFAULT 0 NOT NULL
);

CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    APELLIDOS NVARCHAR(255) NOT NULL,
    EMAIL NVARCHAR(100) UNIQUE NOT NULL,
    CONTRASENA NVARCHAR(255),
    IMAGEN NVARCHAR(255),
    TELEFONO NVARCHAR(20),
    ESTA_ACTIVO BIT DEFAULT 0 NOT NULL,
    ID_ROL INT NOT NULL,
    CONSTRAINT FK_USUARIOS_ROLES FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);

CREATE TABLE KEYS_USUARIOS ( 
    ID_USUARIO INT PRIMARY KEY,
    SALT VARBINARY(MAX) NOT NULL,
    PASSWORD VARBINARY(MAX) NOT NULL,
    CONSTRAINT FK_KEYS_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE DIRECCIONES (
    ID_DIRECCION INT PRIMARY KEY,
    NOMBRE_ETIQUETA NVARCHAR(50),
    CALLE_NUMERO NVARCHAR(255) NOT NULL,
    PISO NVARCHAR(50),
    PUERTA NVARCHAR(50),
    CODIGO_POSTAL NVARCHAR(10) NOT NULL,
    MUNICIPIO NVARCHAR(100) NOT NULL,
    PROVINCIA NVARCHAR(100) NOT NULL,
    LATITUD DECIMAL(10, 8) NOT NULL,
    LONGITUD DECIMAL(10, 8) NOT NULL,
    ES_PRINCIPAL BIT DEFAULT 0 NOT NULL,
    NOTAS_ADICIONALES NVARCHAR(255),
    ID_USUARIO INT NOT NULL,
    CONSTRAINT FK_DIRECCIONES_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE VALIDACIONES (
    ID_VALIDACION INT PRIMARY KEY,
    ESTADO NVARCHAR(255)
);

CREATE TABLE FINCAS (
    ID_FINCA INT PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    DIRECCION NVARCHAR(255) NOT NULL,
    MUNICIPIO NVARCHAR(100) NOT NULL,
    PROVINCIA NVARCHAR(100) NOT NULL,
    LATITUD DECIMAL(10, 8) NOT NULL,
    LONGITUD DECIMAL(10, 8) NOT NULL,
    ESTA_ACTIVA BIT DEFAULT 0 NOT NULL,
    ESTA_VALIDADA INT NOT NULL,
    ID_USUARIO INT NOT NULL, 
    CONSTRAINT FK_FINCAS_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_FINCAS_VALIDACION FOREIGN KEY (ESTA_VALIDADA) REFERENCES VALIDACIONES(ID_VALIDACION) ON DELETE CASCADE
);

CREATE TABLE SUBCATEGORIAS (
    ID_SUBCATEGORIA INT PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(255),
    IMAGEN NVARCHAR(100) NOT NULL,
    ESTA_ACTIVA BIT DEFAULT 0 NOT NULL,
    ID_CATEGORIA INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE UNIDAD_MEDIDAS(
    ID_UNIDAD_MEDIDA INT PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL,
    ESTA_ACTIVA BIT DEFAULT 0 NOT NULL
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(MAX),
    IMAGEN NVARCHAR(255),
    PRECIO_UNIDAD DECIMAL(10, 2) NOT NULL,
    ID_UNIDAD_MEDIDA INT NOT NULL,
    STOCK INT DEFAULT 0 NOT NULL,
    ESTA_ACTIVO BIT DEFAULT 1 NOT NULL,
    ID_FINCA INT NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    ID_SUBCATEGORIA INT NOT NULL,
    CONSTRAINT FK_PRODUCTOS_FINCAS FOREIGN KEY (ID_FINCA) REFERENCES FINCAS(ID_FINCA) ON DELETE CASCADE,
    CONSTRAINT FK_PRODUCTOS_SUBCATEGORIAS FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES SUBCATEGORIAS(ID_SUBCATEGORIA),
    CONSTRAINT FK_PRODUCTOS_CATEGORIAS FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
    CONSTRAINT FK_PRODUCTOS_UNIDAD_MEDIDA FOREIGN KEY (ID_UNIDAD_MEDIDA) REFERENCES UNIDAD_MEDIDAS(ID_UNIDAD_MEDIDA)
);

CREATE TABLE CARRITO_ITEMS (
    ID_CARRITO_ITEM INT PRIMARY KEY,
    CANTIDAD INT DEFAULT 1 NOT NULL,
    ID_USUARIO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CONSTRAINT FK_CARRITO_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_CARRITO_PRODUCTOS FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO) ON DELETE NO ACTION
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO INT PRIMARY KEY,
    FECHA_PEDIDO DATETIME DEFAULT GETDATE() NOT NULL,
    SUBTOTAL DECIMAL(10, 2) NOT NULL, 
    TASA_GESTION DECIMAL(10,2) DEFAULT 0.9 NOT  NULL,
    GASTOS_ENVIO DECIMAL(10, 2) DEFAULT 0 NOT NULL,
    TOTAL DECIMAL(10, 2) NOT NULL,
    ESTADO NVARCHAR(50) DEFAULT N'PENDIENTE' NOT NULL,
    ID_USUARIO INT NOT NULL,
    ID_DIRECCION_ENTREGA INT NOT NULL,
    CONSTRAINT FK_PEDIDOS_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_PEDIDOS_DIRECCIONES FOREIGN KEY (ID_DIRECCION_ENTREGA) REFERENCES DIRECCIONES(ID_DIRECCION)
);

CREATE TABLE DETALLE_PEDIDOS (
    ID_DETALLE_PEDIDO INT PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10, 2) NOT NULL,
    LISTO BIT DEFAULT 0 NOT NULL,
    CONSTRAINT FK_DETALLE_PEDIDOS FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_PRODUCTOS FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE PAGOS (
    ID_PAGO INT PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    PASARELA NVARCHAR(50) DEFAULT N'STRIPE' NOT NULL,
    METODO_PAGO NVARCHAR(50) DEFAULT N'TARJETA' NOT NULL,
    ULTIMOS_DIGITOS_TARJETA NVARCHAR(4),
    ESTADO_PAGO NVARCHAR(50) NOT NULL, 
    TRANSACTION_ID NVARCHAR(255),
    FECHA_PAGO DATETIME DEFAULT GETDATE() NOT NULL,
    CONSTRAINT FK_PAGOS_PEDIDOS FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);

CREATE TABLE MENSAJES (
    ID_MENSAJE INT PRIMARY KEY,
    ID_USUARIO INT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(255) NOT NULL,
    TIPO_CONSULTA NVARCHAR(50) NOT NULL, 
    ASUNTO NVARCHAR(150) NOT NULL,
    CONTENIDO NVARCHAR(MAX) NOT NULL,
    FECHA_ENVIO DATETIME DEFAULT GETDATE(),
    ES_LEIDO BIT DEFAULT 0 NOT NULL,
    ES_RESPONDIDO BIT DEFAULT 0 NOT NULL,
    CONSTRAINT FK_SUGERENCIAS_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

GO

-- PROCEDURES

CREATE PROCEDURE SP_NEXT_ID (@tabla NVARCHAR(50), @siguienteId INT OUTPUT)
AS
    BEGIN
        DECLARE @columna NVARCHAR(60);
        DECLARE @query NVARCHAR(MAX);
        DECLARE @longitud INT = LEN(@tabla);

        IF UPPER(@tabla) = 'MENSAJES'
            SET @columna = 'ID_MENSAJE';
        ELSE IF UPPER(RIGHT(@tabla, 2)) = 'ES'
            SET @columna = 'ID_' + UPPER(LEFT(@tabla, @longitud - 2));
        ELSE
            SET @columna = 'ID_' + UPPER(LEFT(@tabla, @longitud - 1));

        SET @query = N'SELECT @idOut = ISNULL(MAX(' + QUOTENAME(@columna) + '), 0) + 1 FROM ' + QUOTENAME(@tabla);

        EXEC sp_executesql @query, N'@idOut INT OUTPUT', @idOut = @siguienteId OUTPUT;
    END
GO